name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/ci_cd.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 15.x
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install deps and build
        run: |
          npm install
          npm run build
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          cname: dmohamed.com