name: Frontend CI

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/ci_cd.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: 15.x
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install deps and build
        run: |
          npm ci
          npm run build
        env:
          CI: true
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
